name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install playwright
        run: npx playwright install-deps

      - name: install
        run: npm ci

      - name: build
        run: npm run ci